feat: changes to revocation registry definition
hyperledger/anoncreds-spec pull request #82
Opened 2022-09-30 08:37 UTC by morrieinmaas

Signed-off-by: Moriarty <moritz@animo.id>

2022-10-01 15:01 UTC, swcurran commented on spec/data_flow_setup.md
> +    "type": "CL_ACCUM",
Need to discuss if we want to change the data structure as much as that -- e.g. `type` vs. `revocDefType` and `cred_def_id`.  Doesn't really get us far, and may generate a bunch of extra code changes that creates risk.

The `publicKeys` cannot be dropped, so needs to be added back.  Again -- keeping the data structure the same will reduce the code impact, since we are dealing with existing code.

2022-10-01 15:01 UTC, swcurran commented on spec/data_flow_setup.md
> +* `tailsLocation` - The URL pointing to the related tails file
Can't drop the public key and `z` value -- necessary for the crypto.

2022-10-01 15:04 UTC, swcurran requested changes
We'll need to discuss the data structure changes with the devs likely to do the work.  It means that the Indy Method will have to marshal the values from the old to new data structures and then the AnonCreds code will have to be (correctly!) updated to use the new values rather than the old -- all extra work.

Also the dropping of the publicKey is not possible -- it is a necessary data value.

2022-10-01 15:04 UTC, swcurran requested changes
We'll need to discuss the data structure changes with the devs likely to do the work.  It means that the Indy Method will have to marshal the values from the old to new data structures and then the AnonCreds code will have to be (correctly!) updated to use the new values rather than the old -- all extra work.

Also the dropping of the publicKey is not possible -- it is a necessary data value.

2022-10-03 07:05 UTC, morrieinmaas commented
Thanks for the feedback @swcurran - I'll make amends as much as possible. Please just keep me updated about the status of the quotes reply below.

> We'll need to discuss the data structure changes with the devs likely to do the work. It means that the Indy Method will have to marshal the values from the old to new data structures and then the AnonCreds code will have to be (correctly!) updated to use the new values rather than the old -- all extra work.
> 
> Also the dropping of the publicKey is not possible -- it is a necessary data value.

2022-10-03 13:56 UTC, TimoGlastra commented on spec/data_flow_setup.md
> +    "type": "CL_ACCUM",
This is the data type that is used by the AnonCreds library (currently indy-shared-rs and indy-sdk) . When you parse the transaction, indy-sdk / vdr will transform it into the other data model.

2022-10-03 14:11 UTC, TimoGlastra commented
This PR stills needs to be updated with learning from RWOT

2022-10-18 08:41 UTC, morrieinmaas commented
@TimoGlastra @swcurran Anymore feedback on this?

2022-10-21 17:07 UTC, swcurran approved these changes
LGTM

2022-10-24 08:15 UTC, TimoGlastra requested changes

2022-10-24 08:15 UTC, TimoGlastra commented on spec/data_flow_setup.md
> +    "issuanceType": "ISSUANCE_ON_DEMAND",
Issuance type can be removed I think. If we define the revocation registry state as a bit array, the issuancetype doesn't matter. We always get the revocation state. It only matters for the anoncreds specific implementations that do support this type (and is therefore only needed on the indy ledger, not the data model).

2022-10-24 08:15 UTC, TimoGlastra commented on spec/data_flow_setup.md
> +    "type": "CL_ACCUM",
This is missing the `id` property

2022-10-24 08:15 UTC, TimoGlastra commented on spec/data_flow_setup.md
> +* `z` - a public key used to sign the accumulator (described further below)
I think it would be nice to keep make this a nested list, so it follows the structure of the json

```
* publicKeys - describe public keys
    * accumKey - describe accumKey
        * z - describe z
```

2022-10-24 08:15 UTC, TimoGlastra commented on spec/data_flow_setup.md
> +* `type` - the type of revocation registry
`type` is always `CL_ACCUM` at the moment, would be good to document this

2022-10-24 08:15 UTC, TimoGlastra commented on spec/data_flow_setup.md
> +* `cred_def_id` - The credential definition id
Would be good to include references here, e.g. the `schema_id` property in the cred def data model is as follows:

```
The ID of the [[ref:Schema]] on which the [[ref: Credential Definition]] for the offered [[ref:Credential]] is based.

```

Maybe it can be something like:

```
The id of the [[ref: Credential Definition]] on which the [[ref: Revocation Registry]] is based.
```

2022-10-24 08:15 UTC, TimoGlastra commented on spec/data_flow_setup.md
>  the `tailsLocation` input parameter provided by the [[ref: issuer]].
I think we should also update  all references of `PRIVATE_REV_REG` to `Private Revocation Registry Definition` or something like that. To be consistent in the naming, and with the cred def changes

2022-10-24 08:15 UTC, TimoGlastra commented on spec/data_flow_setup.md
>  * `revocDefTyep`: the input parameter `type`
```suggestion
* `revocDefType`: the input parameter `type`
```

2022-10-24 08:15 UTC, TimoGlastra commented on spec/data_flow_setup.md
> +* `revocRegDefId`: the identifier of the associated [[ref: Revocation Registry Definition]]. The
Should we make this more consistent with the revoc reg def?

2022-10-24 08:15 UTC, TimoGlastra commented on spec/data_flow_setup.md
> +* `cred_def_id` - The credential definition id
Does it make sense to have the `cred_def_id` snake_case and all other properties camelCase?

2022-10-24 09:03 UTC, morrieinmaas commented
thx will address today

2022-10-24 15:36 UTC, morrieinmaas commented on spec/data_flow_setup.md
> +* `cred_def_id` - The credential definition id
Was wondering the same. Any opinion on that. That was how it (partially was - see: `* `credDefId`: the input parameter `cred_def_id``, old)

2022-10-24 15:55 UTC, morrieinmaas commented on spec/data_flow_setup.md
> +* `revocRegDefId`: the identifier of the associated [[ref: Revocation Registry Definition]]. The
Sorry not sure what you mean

2022-11-19 19:20 UTC, swcurran commented on spec/data_flow_setup.md
> +    "credDefId": "Ehx3RZSV38pn3MYvxtHhbQ:3:CL:264697:default",
I think if we use this "legacy Indy" example, the "id" and "credDefId", need to be related. E.g. the prefix of the "id" is the value of the "credDefId", as that is the way it is in legacy Indy.   We could, of course, remove the values and just but holders in place -- and update the text above about it being an actual example.

2022-11-19 19:21 UTC, swcurran commented on spec/data_flow_setup.md
> -    "issuanceType": "ISSUANCE_BY_DEFAULT",
While we want to deprecate the "ISSUANCE_ON_DEMAND" feature, I don't think we can simply drop the value from the data structure -- at least not in the 1.0 spec.

2022-11-19 19:23 UTC, swcurran reviewed
While the vast majority of this can be merged, we have to look specifically at the reworking done of the data structures to see if that will work.

2022-11-20 08:13 UTC, TimoGlastra commented on spec/data_flow_setup.md
> -    "issuanceType": "ISSUANCE_BY_DEFAULT",
We can if we also update the revocation list data model. If you have issuance by default none of the items in the list will have a 0 value by default. If you use `ISSUANCE_ON_DEMAND` all values in the list will have a 1 value to start with.

Internally e.g. indy can use this, but I don't think it's needed in the data model if we always use the full state of the revocation list

2022-11-22 17:38 UTC, swcurran approved these changes
LGTM -- thanks!

2022-11-22 17:39 UTC, swcurran commented
@TimoGlastra -- can you please look at this again.  Have your requests for changes been resolved?  If not, please work with @morrieinmaas to make that happen.  Thanks!

2022-11-25 07:48 UTC, TimoGlastra approved these changes
LGTM.

 I think we should have a discussion on casing as Stephen said. Indy is VERY inconsistent in camelCase vs snake_case and mixes and matches. I think we're fine with changing some of the ledger data models casing, as those can be easily transformed locally (and thus be backwards compatible).

For the schema and cred def we changed the camelCase properties to snake_case. We should do the same for the revocation registry, OR we should revert those changes to the other models. My opinion is that a few cosmetic changes to the ledger models are not a problem as we're already changing the way revocation models work. However I also see the other side. This is related to this PR: https://github.com/hyperledger/anoncreds-spec/pull/105

Can't make the upcoming AnonCreds meeting due to the later time, but will try to attend the one after that and possibly discuss this in more detail

2022-11-25 07:48 UTC, TimoGlastra commented on spec/data_flow_setup.md
> +* `revocRegDefId`: the identifier of the associated [[ref: Revocation Registry Definition]]. The
Doesn't matter, we're going to deprecate this object

2022-11-25 07:52 UTC, TimoGlastra commented
@morrieinmaas can you address the merge conflicts? Then we can merge

2022-11-25 09:05 UTC, morrieinmaas commented
> LGTM.
> 
> I think we should have a discussion on casing as Stephen said. Indy is VERY inconsistent in camelCase vs snake_case and mixes and matches. I think we're fine with changing some of the ledger data models casing, as those can be easily transformed locally (and thus be backwards compatible).
> 
> For the schema and cred def we changed the camelCase properties to snake_case. We should do the same for the revocation registry, OR we should revert those changes to the other models. My opinion is that a few cosmetic changes to the ledger models are not a problem as we're already changing the way revocation models work. However I also see the other side. This is related to this PR: #105
> 
> Can't make the upcoming AnonCreds meeting due to the later time, but will try to attend the one after that and possibly discuss this in more detail

Nice one and agreed. Tricky to do naming but let's make this good choices.

I'll address the merge conflicts in a minute

2022-11-25 09:37 UTC, morrieinmaas commented
Not sure how to best go about the not signed off failures here as there seems to be commits not signed off that are not from me.

2022-11-25 18:07 UTC, swcurran commented
Hmm...that's weird -- I've never had that issue before.  I'll see if I can check with @ryjones on what can be done.

2022-11-25 18:17 UTC, swcurran commented
Sigh -- I hate DCO issues.  @TimoGlastra -- probably best if you follow the rebase instructions here: https://github.com/hyperledger/anoncreds-spec/pull/82/checks.  Perhaps @morrieinmaas can do that -- I'm not sure.

2022-11-25 18:29 UTC, merged

2022-11-25 18:31 UTC, swcurran commented
@TimoGlastra @morrieinmaas -- found a way around it. All good now.  Now to fix the merge conflicts in my PR :-)